export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL'

export const GET_TOP_COMMENTS_REQUEST = 'GET_TOP_COMMENTS_REQUEST'
export const GET_TOP_COMMENTS_SUCCESS = 'GET_TOP_COMMENTS_SUCCESS'
export const GET_TOP_COMMENTS_FAIL = 'GET_TOP_COMMENTS_FAIL'

export const GET_COMMENT_BY_ID_REQUEST = 'GET_COMMENT_BY_ID_REQUEST'
export const GET_COMMENT_BY_ID_SUCCESS = 'GET_COMMENT_BY_ID_SUCCESS'
export const GET_COMMENT_BY_ID_FAIL = 'GET_COMMENT_BY_ID_FAIL'

export const WRITE_COMMENT_REQUEST = 'WRITE_COMMENT_REQUEST'
export const WRITE_COMMENT_SUCCESS = 'WRITE_COMMENT_SUCCESS'
export const WRITE_COMMENT_FAIL = 'WRITE_COMMENT_FAIL'

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST'
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS'
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL'

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST'
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
