export const GET_PUBLIC_POSTS_REQUEST = 'GET_PUBLIC_POSTS_REQUEST'
export const GET_PUBLIC_POSTS_SUCCESS = 'GET_PUBLIC_POSTS_SUCCESS'
export const GET_PUBLIC_POSTS_FAIL = 'GET_PUBLIC_POSTS_FAIL'

export const GET_MORE_POSTS_REQUEST = 'GET_MORE_POSTS_REQUEST'
export const GET_MORE_POSTS_SUCCESS = 'GET_MORE_POSTS_SUCCESS'
export const GET_MORE_POSTS_FAIL = 'GET_MORE_POSTS_FAIL'

export const GET_MY_POSTS_REQUEST = 'GET_MY_POSTS_REQUEST'
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS'
export const GET_MY_POSTS_FAIL = 'GET_MY_POSTS_FAIL'

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST'
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS'
export const GET_POST_BY_ID_FAIL = 'GET_POST_BY_ID_FAIL'

export const WRITE_POST_REQUEST = 'WRITE_POST_REQUEST'
export const WRITE_POST_SUCCESS = 'WRITE_POST_SUCCESS'
export const WRITE_POST_FAIL = 'WRITE_POST_FAIL'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'
